name: WorkerAnts
version: '${project.version}'
main: moe.sandie.workerants.WorkerAnts
api-version: 1.19
author: sandie
description: Create npc workers you can upgrade and get items/money from
softdepend: [ Citizens, Vault ]
commands:
  worker:
    description: gives npc egg to player
    usage: /<command>
  resetnpcs:
    description: reset npc ids
    usage: /<command>